sudo: false
language: python
python:
- '3.6'
install:
- source .env
- pip3 install -r requirements.txt
script: flask test
deploy:
  provider: heroku
  app: <APP_NAME>
  api_key:
    secure: <API_KEY>
notifications:
  email: false
  slack:
    secure: <API_KEY>
